# -*- coding: utf-8 -*-
"""LDD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhK2uv5MNhmSnjW5QbHrrrswuYRMDCAs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Load the dataset from Excel into a pandas DataFrame
data = pd.read_excel("Hackathon_Data - Anonymised- v2.xlsx")

data

data=data.drop(0)

# Select the relevant attributes for clustering
attributes = ['BCLOT', 'A/G RAT', 'DBIL', 'IBIL', 'TBIL', 'TGLO', 'TREP', 'ALB', 'GGT', 'SGOT', 'SGPT', 'ALKPO4']

# Perform data preprocessing - scale the attributes
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data[attributes])

# Apply the elbow method
inertia = []
k_values = range(1, 11)  # Test k values from 1 to 10

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    inertia.append(kmeans.inertia_)

# Plot the elbow curve
plt.plot(k_values, inertia, 'bo-')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()